### PR TITLE
Update blueprint-traveltimesbywaze.yaml

### PR DESCRIPTION
**Pull request by elwing00**
Added Source URL to be able to update/import

### CODE REVIEW

**Comment by dinki** [comment]
Doesn't this happen automatically?   I did recently have to update all BP install links to get rid of the spaces that were breaking things but I THOUGHT that once a user installs these it will allow for updating without the need to add this line?

**Comment by elwing00** [comment]
It wouldn't let me, said "no source_url" as the error.  All the other blueprints have a source url in them.

**Comment by dinki** [comment]
I did this search and did not find anything like that in the repo:

https://github.com/search?q=repo%3Adinki%2FView-Assist+source&type=code

Now the local copies in HA will have that value but it is inserted on install.

image

**Comment by elwing00** [comment]
maybe just my install - feel free to reject the PR

**Pull request closed without merging**
