### PR TITLE
Voice satellite support

### PR DESCRIPTION
**Pull request by michelle-avery**
This adds support for Voice Satellites as mics for the dashboard and device control blueprints.

### CODE REVIEW

**Comment by dinki** [comment]
Hey thanks for the PR.  I'm neck deep in work 'challenges' so wondering if you could give me a nutshell on what your PR is adding/changing?  Also what is your handle on Discord?  I think you are on the server.  If not, disregard :)

**Comment by michelle-avery** [comment]
I'm miniconfig  on the Discord channel. This lets you use the new ViewAssist dashboard with assist_satellites - mostly Wyoming Satellites running on Linux devices. I did it in a way that supports esphome voice satellites as well, but I don't know what the likelihood is of someone  using that with a browser-capable display. In theory though, you could use one of the tiny m5stack atom echos to control a browser running on a different device.

**Comment by dinki** [comment]
Still have not tried this but did review it tonight and this looks excellent.  I want to support any and all voice satellites both with and without screens.  Thanks for sharing this.  I hope to give it a spin this weekend and the merge in.

**Comment by dinki** [comment]
Thanks again for your work on this.  Approved!

**Pull request merged**
